version: '2'
services:
  unms:
    build: https://github.com/Leor47/docker-unms.git
    image: clouduisp.azurecr.io/unms:latest
    container_name: unms
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2055:2055/udp
    environment:
      - TZ=America/Costa_Rica
    volumes:
     - uisp-volume:/config
volumes:
  uisp-volume:
    driver: azure_file
    driver_opts:
      share_name: uisp
      storage_account_name: greendatastore