apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unms
  name: unms
  namespace: isp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unms
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Costa_Rica
        image: clouduisp.azurecr.io/unms:latest
        imagePullPolicy: ""
        name: unms
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 2055
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: uisp-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: uisp-volume
        persistentVolumeClaim:
          claimName: uisp-volume
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: uisp-volume
  namespace: isp
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Standard_LRS
  kind: Managed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: uisp-volume
  name: uisp-volume
  namespace: isp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  name: unms
  namespace: isp
spec:
  type: ClusterIP
  selector:
    app: unms
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
