apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      --file docker-compose.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: unms
  name: unms
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: unms
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          --file docker-compose.yml convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: unms
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Costa_Rica
        image: clouduisp.azurecr.io/unms:latest
        imagePullPolicy: ""
        name: unms
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2055
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: dockerunms-uisp-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: dockerunms-uisp-volume
        persistentVolumeClaim:
          claimName: dockerunms-uisp-volume
status: {}
