apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: unms
  name: unms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unms
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unms
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Costa_Rica
        image: clouduisp.azurecr.io/unms:latest
        imagePullPolicy: ""
        name: unms
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 2055
          protocol: UDP
        resources: {}
        volumeMounts:
        - mountPath: /config
          name: dockerunms-uisp-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: dockerunms-uisp-volume
        persistentVolumeClaim:
          claimName: dockerunms-uisp-volume
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: unms
  name: unms
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "2055"
    port: 2055
    protocol: UDP
    targetPort: 2055
  selector:
    app: unms
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: dockerunms-uisp-volume
  name: dockerunms-uisp-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi


  