apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: unms
  name: unms
  namespace: uisp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unms
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: unms      
    spec:
      containers:
      - env:
        - name: TZ
          value: America/Costa_Rica
        image: clouduisp.azurecr.io/unms:latest
        imagePullPolicy: ""
        name: unms
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        - containerPort: 2055
          protocol: UDP
        volumeMounts:
        - mountPath: /config
          name: uisp-volume-pod
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: uisp-volume-pod
          persistentVolumeClaim:
            claimName: uisp-disk-pvc
---     
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: static-disk
  namespace: uisp
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uisp-disk-pv
  namespace: uisp  
spec:
  capacity:
    storage: 16Gi
  storageClassName: static-disk
  claimRef:
    name: uisp-disk-pvc
    namespace: uisp
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  azureDisk:
    kind: Managed
    diskName: uisp-disk
    diskURI: /subscriptions/773ff44c-9f7e-4137-abab-4d4c5c6bd073/resourceGroups/MC_isp_ispCluster_eastus/providers/Microsoft.Compute/disks/uisp-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uisp-disk-pvc
  namespace: uisp
spec:
  storageClassName: static-disk
  volumeName: uisp-disk-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 16Gi
---
apiVersion: v1
kind: Service
metadata:
  name: unms-service
  namespace: uisp
spec:  
  selector:
    app: unms
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  - name: "443"
    port: 443
    targetPort: 443
  - name: "2055"
    port: 2055
    protocol: UDP
    targetPort: 2055
  type: ClusterIP
